export const seededUsers: Array<{
  id: string;
  displayName: string;
  verified: boolean;
  online: boolean;
  age: number;
  city: string;
  area: string;
  bio: string;
  vibe: string;
  rating: number;
  meetupCount: number;
  avatarUrl: string;
  photoUrls: string[];
  intent: string;
  interests: string[];
}> = [
  {
    id: 'user-me',
    displayName: 'Никита М',
    verified: true,
    online: true,
    age: 28,
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Дизайнер. Люблю долгие прогулки и тихие бары. Ищу людей, с которыми можно собраться без долгого планирования.',
    vibe: 'Спокойно',
    rating: 4.8,
    meetupCount: 12,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita-evening',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita-city',
    ],
    intent: 'both',
    interests: ['Кофе', 'Бары', 'Настолки', 'Кино', 'Книги', 'Велик'],
  },
  {
    id: 'user-anya',
    displayName: 'Аня К',
    verified: true,
    online: true,
    age: 27,
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Архитектор. Люблю тихие бары и долгие разговоры. Часто хожу на выставки и в книжный.',
    vibe: 'Спокойно',
    rating: 4.9,
    meetupCount: 23,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna-gallery',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna-park',
    ],
    intent: 'dating',
    interests: ['Кофе', 'Настолки', 'Книги', 'Кино', 'Бары', 'Выставки'],
  },
  {
    id: 'user-mark',
    displayName: 'Марк С',
    verified: true,
    online: true,
    age: 30,
    city: 'Москва',
    area: 'Патрики',
    bio: 'Люблю бары, кино и быстрые планы без долгой переписки.',
    vibe: 'Шумно',
    rating: 4.4,
    meetupCount: 9,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark-night',
    ],
    intent: 'friendship',
    interests: ['Бары', 'Кино'],
  },
  {
    id: 'user-liza',
    displayName: 'Лиза П',
    verified: true,
    online: false,
    age: 25,
    city: 'Москва',
    area: 'Хамовники',
    bio: 'Люблю йогу, книги и спокойные встречи без шума.',
    vibe: 'Спокойно',
    rating: 4.6,
    meetupCount: 8,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza-books',
    ],
    intent: 'both',
    interests: ['Йога', 'Книги'],
  },
  {
    id: 'user-dima',
    displayName: 'Дима Р',
    verified: false,
    online: false,
    age: 29,
    city: 'Москва',
    area: 'Сокол',
    bio: 'Бег, велик и встречи, где можно сразу перейти к делу.',
    vibe: 'Активно',
    rating: 4.3,
    meetupCount: 7,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima-bike',
    ],
    intent: 'friendship',
    interests: ['Бег', 'Велик'],
  },
  {
    id: 'user-sonya',
    displayName: 'Соня М',
    verified: true,
    online: true,
    age: 26,
    city: 'Москва',
    area: 'Замоскворечье',
    bio: 'Люблю театр, готовку и спокойные встречи в центре.',
    vibe: 'Спокойно',
    rating: 4.7,
    meetupCount: 11,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya-theatre',
    ],
    intent: 'both',
    interests: ['Театр', 'Готовка'],
  },
  {
    id: 'user-oleg',
    displayName: 'Олег К',
    verified: true,
    online: false,
    age: 31,
    city: 'Москва',
    area: 'Центр',
    bio: 'Музыка, бары и спонтанные вечера после работы.',
    vibe: 'Шумно',
    rating: 4.5,
    meetupCount: 10,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg-music',
    ],
    intent: 'friendship',
    interests: ['Музыка', 'Бары'],
  },
];

export const seededEvents: Array<{
  id: string;
  title: string;
  emoji: string;
  startsAt: Date;
  durationMinutes: number;
  place: string;
  distanceKm: number;
  vibe: string;
  tone: 'warm' | 'evening' | 'sage';
  joinMode?: 'open' | 'request';
  lifestyle?: 'zozh' | 'neutral' | 'anti';
  priceMode?: 'free' | 'fixed' | 'from' | 'upto' | 'range' | 'split';
  priceAmountFrom?: number | null;
  priceAmountTo?: number | null;
  accessMode?: 'open' | 'request' | 'free';
  genderMode?: 'all' | 'male' | 'female';
  visibilityMode?: 'public' | 'friends';
  hostNote?: string;
  description: string;
  partnerName?: string;
  partnerOffer?: string;
  capacity: number;
  isCalm: boolean;
  isNewcomers: boolean;
  isDate: boolean;
  hostId: string;
}> = [
  {
    id: 'e1',
    title: 'Винный вечер на крыше',
    emoji: '🍷',
    startsAt: new Date('2026-04-19T20:00:00.000Z'),
    durationMinutes: 120,
    place: 'Brix Wine, Покровка 12',
    distanceKm: 1.2,
    vibe: 'Спокойно',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'anti',
    priceMode: 'range',
    priceAmountFrom: 1800,
    priceAmountTo: 2800,
    accessMode: 'open',
    genderMode: 'all',
    visibilityMode: 'public',
    hostNote: 'Знакомимся за бокалом, без спешки.',
    description:
      'Камерный вечер на крыше с винами от локального сомелье. Без программы и спешки, просто хороший разговор, виды на город и пара бокалов. Подойдёт, если хочешь познакомиться без давления.',
    partnerName: 'Brix Wine',
    partnerOffer: '−15% на бокалы для участников',
    capacity: 10,
    isCalm: true,
    isNewcomers: true,
    isDate: true,
    hostId: 'user-anya',
  },
  {
    id: 'e2',
    title: 'Вечерняя пробежка по бульварам',
    emoji: '🌿',
    startsAt: new Date('2026-04-20T19:30:00.000Z'),
    durationMinutes: 90,
    place: 'Чистые пруды',
    distanceKm: 0.6,
    vibe: 'Активно',
    tone: 'sage',
    joinMode: 'open',
    lifestyle: 'zozh',
    priceMode: 'free',
    accessMode: 'free',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Легкая пробежка без гонки и с остановкой на кофе после финиша.',
    capacity: 8,
    isCalm: false,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-mark',
  },
  {
    id: 'e3',
    title: 'Настолки и кофе',
    emoji: '♟️',
    startsAt: new Date('2026-04-20T19:00:00.000Z'),
    durationMinutes: 180,
    place: 'Кафе Заря, Хохловский',
    distanceKm: 0.9,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'upto',
    priceAmountTo: 900,
    accessMode: 'open',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Небольшая компания, кофе и настолки до закрытия.',
    capacity: 12,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-sonya',
  },
  {
    id: 'e4',
    title: 'Кино под открытым небом',
    emoji: '🎬',
    startsAt: new Date('2026-04-21T21:00:00.000Z'),
    durationMinutes: 150,
    place: 'Парк Горького',
    distanceKm: 3.4,
    vibe: 'Свидание',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'from',
    priceAmountFrom: 3500,
    accessMode: 'free',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Летний киносеанс под открытым небом и короткая прогулка после фильма.',
    capacity: 30,
    isCalm: true,
    isNewcomers: false,
    isDate: true,
    hostId: 'user-mark',
  },
  {
    id: 'e5',
    title: 'Камерный ужин по заявкам',
    emoji: '🍝',
    startsAt: new Date('2026-04-20T18:30:00.000Z'),
    durationMinutes: 150,
    place: 'Солянка 5',
    distanceKm: 0.7,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'request',
    lifestyle: 'neutral',
    priceMode: 'range',
    priceAmountFrom: 1200,
    priceAmountTo: 2200,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Хочу собрать маленькую спокойную компанию.',
    description: 'Ужин в маленькой компании. Сначала заявка, потом подтверждение хостом.',
    capacity: 5,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-me',
  },
];

export const seededPosters: Array<{
  id: string;
  city: string;
  category:
    | 'concert'
    | 'sport'
    | 'exhibition'
    | 'theatre'
    | 'standup'
    | 'festival'
    | 'cinema';
  title: string;
  emoji: string;
  startsAt: Date;
  dateLabel: string;
  timeLabel: string;
  venue: string;
  address: string;
  distanceKm: number;
  priceFrom: number;
  ticketUrl: string;
  provider: string;
  tone: 'warm' | 'evening' | 'sage';
  tags: string[];
  description: string;
  isFeatured: boolean;
}> = [
  {
    id: 'ps1',
    city: 'Москва',
    category: 'concert',
    title: 'Молчат Дома · большой концерт',
    emoji: '🎸',
    startsAt: new Date('2026-04-26T20:00:00.000Z'),
    dateLabel: 'Сб, 26 апр',
    timeLabel: '20:00',
    venue: 'Adrenaline Stadium',
    address: 'Ленинградское ш. 80',
    distanceKm: 4.2,
    priceFrom: 3500,
    ticketUrl: 'https://afisha.yandex.ru',
    provider: 'Яндекс Афиша',
    tone: 'evening',
    tags: ['пост-панк', '18+', 'танцпол'],
    description: 'Юбилейный тур группы. Новый альбом и старые хиты.',
    isFeatured: true,
  },
  {
    id: 'ps2',
    city: 'Москва',
    category: 'sport',
    title: 'ЦСКА — Спартак · дерби',
    emoji: '⚽',
    startsAt: new Date('2026-04-27T19:00:00.000Z'),
    dateLabel: 'Вс, 27 апр',
    timeLabel: '19:00',
    venue: 'ВЭБ Арена',
    address: '3-я Песчаная ул. 2',
    distanceKm: 8.1,
    priceFrom: 1200,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'warm',
    tags: ['футбол', 'РПЛ', 'семейный сектор'],
    description: 'Главное московское дерби сезона. Атмосфера и фанатские перформансы.',
    isFeatured: true,
  },
  {
    id: 'ps3',
    city: 'Москва',
    category: 'exhibition',
    title: 'Кандинский. Контрапункт',
    emoji: '🎨',
    startsAt: new Date('2026-04-22T11:00:00.000Z'),
    dateLabel: 'Каждый день',
    timeLabel: '11:00–22:00',
    venue: 'Третьяковка на Крымском',
    address: 'Крымский Вал 10',
    distanceKm: 3.4,
    priceFrom: 800,
    ticketUrl: 'https://tretyakov.ru',
    provider: 'Третьяковка',
    tone: 'sage',
    tags: ['живопись', 'до 31 мая'],
    description: 'Большая ретроспектива с архивными работами и звуковой инсталляцией.',
    isFeatured: true,
  },
  {
    id: 'ps4',
    city: 'Москва',
    category: 'standup',
    title: 'Женский стендап · новые имена',
    emoji: '🎤',
    startsAt: new Date('2026-04-25T20:30:00.000Z'),
    dateLabel: 'Пт, 25 апр',
    timeLabel: '20:30',
    venue: 'StandUp Club #1',
    address: 'Новый Арбат 21',
    distanceKm: 2.7,
    priceFrom: 1500,
    ticketUrl: 'https://standupstore.ru',
    provider: 'StandUp Store',
    tone: 'warm',
    tags: ['юмор', '18+'],
    description: 'Вечер новых комиков с плотным лайнапом и камерной посадкой.',
    isFeatured: true,
  },
  {
    id: 'ps5',
    city: 'Москва',
    category: 'theatre',
    title: 'Гамлет',
    emoji: '🎭',
    startsAt: new Date('2026-04-24T19:00:00.000Z'),
    dateLabel: 'Чт, 24 апр',
    timeLabel: '19:00',
    venue: 'Театр на Бронной',
    address: 'Малая Бронная 4',
    distanceKm: 2.9,
    priceFrom: 2200,
    ticketUrl: 'https://teatrnabronnoy.ru',
    provider: 'Театр на Бронной',
    tone: 'evening',
    tags: ['драма', 'классика'],
    description: 'Современное прочтение Шекспира с минималистичной сценографией.',
    isFeatured: true,
  },
  {
    id: 'ps6',
    city: 'Москва',
    category: 'festival',
    title: 'Geek Picnic',
    emoji: '🎡',
    startsAt: new Date('2026-05-03T12:00:00.000Z'),
    dateLabel: 'Сб, 3 мая',
    timeLabel: '12:00',
    venue: 'Парк Горького',
    address: 'Крымский Вал 9',
    distanceKm: 3.5,
    priceFrom: 1800,
    ticketUrl: 'https://geek-picnic.me',
    provider: 'Geek Picnic',
    tone: 'sage',
    tags: ['технологии', 'лекторий', 'open-air'],
    description: 'Городской фестиваль технологий, науки и интерактивных зон.',
    isFeatured: false,
  },
  {
    id: 'ps7',
    city: 'Москва',
    category: 'concert',
    title: 'Хадн Дадн',
    emoji: '🎶',
    startsAt: new Date('2026-04-28T20:00:00.000Z'),
    dateLabel: 'Пн, 28 апр',
    timeLabel: '20:00',
    venue: '16 Тонн',
    address: 'Пресненский Вал 6с1',
    distanceKm: 4.8,
    priceFrom: 2500,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'evening',
    tags: ['инди', 'концерт'],
    description: 'Тихий, нервный и очень городской концерт для своих.',
    isFeatured: false,
  },
  {
    id: 'ps8',
    city: 'Москва',
    category: 'cinema',
    title: 'Ночь короткого метра',
    emoji: '🎬',
    startsAt: new Date('2026-04-26T22:00:00.000Z'),
    dateLabel: 'Сб, 26 апр',
    timeLabel: '22:00',
    venue: 'Каро Октябрь',
    address: 'Новый Арбат 24',
    distanceKm: 2.2,
    priceFrom: 900,
    ticketUrl: 'https://karofilm.ru',
    provider: 'КАРО',
    tone: 'warm',
    tags: ['короткий метр', 'ночной показ'],
    description: 'Сборник короткометражек с обсуждением после сеанса.',
    isFeatured: false,
  },
  {
    id: 'ps9',
    city: 'Москва',
    category: 'exhibition',
    title: 'Новая графика',
    emoji: '🖼️',
    startsAt: new Date('2026-04-23T12:00:00.000Z'),
    dateLabel: 'Каждый день',
    timeLabel: '12:00–21:00',
    venue: 'Гараж',
    address: 'Крымский Вал 9с32',
    distanceKm: 3.5,
    priceFrom: 700,
    ticketUrl: 'https://garagemca.org',
    provider: 'Garage',
    tone: 'sage',
    tags: ['графика', 'современное искусство'],
    description: 'Групповая выставка молодых художников с акцентом на печатные техники.',
    isFeatured: false,
  },
  {
    id: 'ps10',
    city: 'Москва',
    category: 'festival',
    title: 'Фестиваль кофе и винила',
    emoji: '☕',
    startsAt: new Date('2026-04-27T13:00:00.000Z'),
    dateLabel: 'Вс, 27 апр',
    timeLabel: '13:00',
    venue: 'Хлебозавод',
    address: 'Новодмитровская 1',
    distanceKm: 6.0,
    priceFrom: 0,
    ticketUrl: 'https://afisha.ru',
    provider: 'Афиша',
    tone: 'warm',
    tags: ['кофе', 'маркет', 'бесплатно'],
    description: 'Обжарщики, виниловые сеты, маркет локальных брендов и дегустации.',
    isFeatured: false,
  },
  {
    id: 'ps11',
    city: 'Москва',
    category: 'sport',
    title: 'Ночной забег по центру',
    emoji: '🏃',
    startsAt: new Date('2026-04-29T21:00:00.000Z'),
    dateLabel: 'Вт, 29 апр',
    timeLabel: '21:00',
    venue: 'Лужники',
    address: 'Лужнецкая наб. 24',
    distanceKm: 7.2,
    priceFrom: 2000,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'sage',
    tags: ['бег', '10 км', 'ночь'],
    description: 'Городской массовый забег с вечерним светом и музыкой на маршруте.',
    isFeatured: false,
  },
  {
    id: 'ps12',
    city: 'Москва',
    category: 'theatre',
    title: 'Лебединое озеро',
    emoji: '🩰',
    startsAt: new Date('2026-04-30T19:00:00.000Z'),
    dateLabel: 'Ср, 30 апр',
    timeLabel: '19:00',
    venue: 'Большой театр',
    address: 'Театральная пл. 1',
    distanceKm: 1.9,
    priceFrom: 4500,
    ticketUrl: 'https://bolshoi.ru',
    provider: 'Большой театр',
    tone: 'evening',
    tags: ['балет', 'классика'],
    description: 'Классическая постановка в исторической сцене Большого театра.',
    isFeatured: false,
  },
];
