export const seededUsers: Array<{
  id: string;
  displayName: string;
  verified: boolean;
  online: boolean;
  age: number;
  gender: 'male' | 'female';
  city: string;
  area: string;
  bio: string;
  vibe: string;
  rating: number;
  meetupCount: number;
  avatarUrl: string;
  photoUrls: string[];
  intent: string;
  interests: string[];
}> = [
  {
    id: 'user-me',
    displayName: 'Никита М',
    verified: true,
    online: true,
    age: 28,
    gender: 'male',
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Дизайнер. Люблю долгие прогулки и тихие бары. Ищу людей, с которыми можно собраться без долгого планирования.',
    vibe: 'Спокойно',
    rating: 4.8,
    meetupCount: 12,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita-evening',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita-city',
    ],
    intent: 'both',
    interests: ['Кофе', 'Бары', 'Настолки', 'Кино', 'Книги', 'Велик'],
  },
  {
    id: 'user-anya',
    displayName: 'Аня К',
    verified: true,
    online: true,
    age: 27,
    gender: 'female',
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Архитектор. Люблю тихие бары и долгие разговоры. Часто хожу на выставки и в книжный.',
    vibe: 'Спокойно',
    rating: 4.9,
    meetupCount: 23,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna-gallery',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Anna-park',
    ],
    intent: 'dating',
    interests: ['Кофе', 'Настолки', 'Книги', 'Кино', 'Бары', 'Выставки'],
  },
  {
    id: 'user-mark',
    displayName: 'Марк С',
    verified: true,
    online: true,
    age: 30,
    gender: 'male',
    city: 'Москва',
    area: 'Патрики',
    bio: 'Люблю бары, кино и быстрые планы без долгой переписки.',
    vibe: 'Шумно',
    rating: 4.4,
    meetupCount: 9,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark-night',
    ],
    intent: 'friendship',
    interests: ['Бары', 'Кино'],
  },
  {
    id: 'user-liza',
    displayName: 'Лиза П',
    verified: true,
    online: false,
    age: 25,
    gender: 'female',
    city: 'Москва',
    area: 'Хамовники',
    bio: 'Люблю йогу, книги и спокойные встречи без шума.',
    vibe: 'Спокойно',
    rating: 4.6,
    meetupCount: 8,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza-books',
    ],
    intent: 'both',
    interests: ['Йога', 'Книги'],
  },
  {
    id: 'user-dima',
    displayName: 'Дима Р',
    verified: false,
    online: false,
    age: 29,
    gender: 'male',
    city: 'Москва',
    area: 'Сокол',
    bio: 'Бег, велик и встречи, где можно сразу перейти к делу.',
    vibe: 'Активно',
    rating: 4.3,
    meetupCount: 7,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima-bike',
    ],
    intent: 'friendship',
    interests: ['Бег', 'Велик'],
  },
  {
    id: 'user-sonya',
    displayName: 'Соня М',
    verified: true,
    online: true,
    age: 26,
    gender: 'female',
    city: 'Москва',
    area: 'Замоскворечье',
    bio: 'Люблю театр, готовку и спокойные встречи в центре.',
    vibe: 'Спокойно',
    rating: 4.7,
    meetupCount: 11,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya-theatre',
    ],
    intent: 'both',
    interests: ['Театр', 'Готовка'],
  },
  {
    id: 'user-oleg',
    displayName: 'Олег К',
    verified: true,
    online: false,
    age: 31,
    gender: 'male',
    city: 'Москва',
    area: 'Центр',
    bio: 'Музыка, бары и спонтанные вечера после работы.',
    vibe: 'Шумно',
    rating: 4.5,
    meetupCount: 10,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg',
    photoUrls: [
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg',
      'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg-music',
    ],
    intent: 'friendship',
    interests: ['Музыка', 'Бары'],
  },
];

export const seededEvents: Array<{
  id: string;
  title: string;
  emoji: string;
  startsAt: Date;
  durationMinutes: number;
  place: string;
  distanceKm: number;
  latitude?: number;
  longitude?: number;
  vibe: string;
  tone: 'warm' | 'evening' | 'sage';
  joinMode?: 'open' | 'request';
  lifestyle?: 'zozh' | 'neutral' | 'anti';
  priceMode?: 'free' | 'fixed' | 'from' | 'upto' | 'range' | 'split';
  priceAmountFrom?: number | null;
  priceAmountTo?: number | null;
  accessMode?: 'open' | 'request' | 'free';
  genderMode?: 'all' | 'male' | 'female';
  visibilityMode?: 'public' | 'friends';
  hostNote?: string;
  description: string;
  partnerName?: string;
  partnerOffer?: string;
  isAfterDark?: boolean;
  afterDarkCategory?: string;
  afterDarkGlow?: string;
  dressCode?: string;
  ageRange?: string;
  ratioLabel?: string;
  consentRequired?: boolean;
  rules?: string[];
  capacity: number;
  isCalm: boolean;
  isNewcomers: boolean;
  isDate: boolean;
  hostId: string;
}> = [
  {
    id: 'e1',
    title: 'Винный вечер на крыше',
    emoji: '🍷',
    startsAt: new Date('2026-04-19T20:00:00.000Z'),
    durationMinutes: 120,
    place: 'Brix Wine, Покровка 12',
    distanceKm: 1.2,
    latitude: 55.7579,
    longitude: 37.6486,
    vibe: 'Спокойно',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'anti',
    priceMode: 'range',
    priceAmountFrom: 1800,
    priceAmountTo: 2800,
    accessMode: 'open',
    genderMode: 'all',
    visibilityMode: 'public',
    hostNote: 'Знакомимся за бокалом, без спешки.',
    description:
      'Камерный вечер на крыше с винами от локального сомелье. Без программы и спешки, просто хороший разговор, виды на город и пара бокалов. Подойдёт, если хочешь познакомиться без давления.',
    partnerName: 'Brix Wine',
    partnerOffer: '−15% на бокалы для участников',
    capacity: 10,
    isCalm: true,
    isNewcomers: true,
    isDate: true,
    hostId: 'user-anya',
  },
  {
    id: 'e2',
    title: 'Вечерняя пробежка по бульварам',
    emoji: '🌿',
    startsAt: new Date('2026-04-23T19:30:00.000Z'),
    durationMinutes: 90,
    place: 'Чистые пруды',
    distanceKm: 0.6,
    latitude: 55.7658,
    longitude: 37.6388,
    vibe: 'Активно',
    tone: 'sage',
    joinMode: 'open',
    lifestyle: 'zozh',
    priceMode: 'free',
    accessMode: 'free',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Легкая пробежка без гонки и с остановкой на кофе после финиша.',
    capacity: 8,
    isCalm: false,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-mark',
  },
  {
    id: 'e3',
    title: 'Настолки и кофе',
    emoji: '♟️',
    startsAt: new Date('2026-04-23T19:00:00.000Z'),
    durationMinutes: 180,
    place: 'Кафе Заря, Хохловский',
    distanceKm: 0.9,
    latitude: 55.7568,
    longitude: 37.6482,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'upto',
    priceAmountTo: 900,
    accessMode: 'open',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Небольшая компания, кофе и настолки до закрытия.',
    capacity: 12,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-sonya',
  },
  {
    id: 'e4',
    title: 'Кино под открытым небом',
    emoji: '🎬',
    startsAt: new Date('2026-04-24T21:00:00.000Z'),
    durationMinutes: 150,
    place: 'Парк Горького',
    distanceKm: 3.4,
    latitude: 55.7304,
    longitude: 37.6017,
    vibe: 'Свидание',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'from',
    priceAmountFrom: 3500,
    accessMode: 'free',
    genderMode: 'all',
    visibilityMode: 'public',
    description: 'Летний киносеанс под открытым небом и короткая прогулка после фильма.',
    capacity: 30,
    isCalm: true,
    isNewcomers: false,
    isDate: true,
    hostId: 'user-mark',
  },
  {
    id: 'e5',
    title: 'Камерный ужин по заявкам',
    emoji: '🍝',
    startsAt: new Date('2026-04-24T18:30:00.000Z'),
    durationMinutes: 150,
    place: 'Солянка 5',
    distanceKm: 0.7,
    latitude: 55.7538,
    longitude: 37.6402,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'request',
    lifestyle: 'neutral',
    priceMode: 'range',
    priceAmountFrom: 1200,
    priceAmountTo: 2200,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Хочу собрать маленькую спокойную компанию.',
    description: 'Ужин в маленькой компании. Сначала заявка, потом подтверждение хостом.',
    capacity: 5,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-me',
  },
  {
    id: 'ad1',
    title: 'Velvet Room · Speakeasy',
    emoji: '🥃',
    startsAt: new Date('2026-04-25T20:00:00.000Z'),
    durationMinutes: 240,
    place: 'Китай-город',
    distanceKm: 1.4,
    latitude: 55.7572,
    longitude: 37.6354,
    vibe: 'Тихий джаз, тёмный бархат, разговоры до утра',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'anti',
    priceMode: 'from',
    priceAmountFrom: 2500,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Знаю всех бартендеров, коктейли с историей.',
    description: 'Закрытый speakeasy на 30 мест. Живой джаз, авторские коктейли и мягкий вход для своих.',
    isAfterDark: true,
    afterDarkCategory: 'nightlife',
    afterDarkGlow: 'magenta',
    dressCode: 'Smart elegant',
    ageRange: '25–40',
    ratioLabel: 'Mixed',
    consentRequired: false,
    rules: ['Без съёмки в зале', 'Не больше +1', 'Тишина у бара'],
    capacity: 30,
    isCalm: false,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-anya',
  },
  {
    id: 'ad2',
    title: 'Blind Dinner · Round 7',
    emoji: '🕯️',
    startsAt: new Date('2026-04-25T17:00:00.000Z'),
    durationMinutes: 180,
    place: 'Патриаршие',
    distanceKm: 2.1,
    latitude: 55.7641,
    longitude: 37.5931,
    vibe: 'Шесть пар, шесть смен блюд, без телефонов',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'from',
    priceAmountFrom: 6500,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Подбираю пары вручную по анкетам.',
    description: 'Слепой ужин, где пары собираются вручную по анкетам и общему ритму вечера.',
    isAfterDark: true,
    afterDarkCategory: 'dating',
    afterDarkGlow: 'violet',
    dressCode: 'Cocktail',
    ageRange: '27–37',
    ratioLabel: '50/50 М/Ж',
    consentRequired: false,
    rules: ['Телефоны на входе', 'Без обмена контактами до десерта', 'Verified profile only'],
    capacity: 12,
    isCalm: true,
    isNewcomers: false,
    isDate: true,
    hostId: 'user-sonya',
  },
  {
    id: 'ad3',
    title: 'Banya Night · Sauna Social',
    emoji: '♨️',
    startsAt: new Date('2026-04-26T18:00:00.000Z'),
    durationMinutes: 240,
    place: 'Хамовники',
    distanceKm: 3.2,
    latitude: 55.7308,
    longitude: 37.5737,
    vibe: 'Парная, чан, чай, тихие разговоры',
    tone: 'sage',
    joinMode: 'request',
    lifestyle: 'zozh',
    priceMode: 'from',
    priceAmountFrom: 4500,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Снимаю целую банную смену. Только для своих.',
    description: 'Закрытая баня на компанию. Парение, чан, чайная церемония и мягкий social формат.',
    isAfterDark: true,
    afterDarkCategory: 'wellness',
    afterDarkGlow: 'cyan',
    dressCode: 'Towel / купальник',
    ageRange: '24–42',
    ratioLabel: 'Mixed',
    consentRequired: true,
    rules: ['Body-positive пространство', 'Без алкоголя в парной', 'Никакой съёмки'],
    capacity: 20,
    isCalm: true,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-liza',
  },
  {
    id: 'ad4',
    title: 'After Hours · Underground',
    emoji: '🔮',
    startsAt: new Date('2026-04-26T22:30:00.000Z'),
    durationMinutes: 300,
    place: 'Курская',
    distanceKm: 2.8,
    latitude: 55.7574,
    longitude: 37.6599,
    vibe: 'Техно-сет, дым, лазеры, до рассвета',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'anti',
    priceMode: 'from',
    priceAmountFrom: 1800,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Резидент из Берлина, локация до старта закрыта.',
    description: 'After-party в индустриальном пространстве. Адрес отправим ближе к старту.',
    isAfterDark: true,
    afterDarkCategory: 'nightlife',
    afterDarkGlow: 'magenta',
    dressCode: 'Free / dark',
    ageRange: '23–35',
    ratioLabel: 'Mixed',
    consentRequired: false,
    rules: ['Адрес за 2 часа до старта', 'No photos policy', 'Verified only'],
    capacity: 80,
    isCalm: false,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-oleg',
  },
  {
    id: 'ad5',
    title: 'Speed Dating · 30+',
    emoji: '💋',
    startsAt: new Date('2026-04-24T16:30:00.000Z'),
    durationMinutes: 150,
    place: 'Тверская',
    distanceKm: 1.1,
    latitude: 55.7646,
    longitude: 37.6057,
    vibe: '12 свиданий по 6 минут, бокал просекко, итоги в приложении',
    tone: 'evening',
    joinMode: 'open',
    lifestyle: 'neutral',
    priceMode: 'from',
    priceAmountFrom: 3500,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Веду такие вечера 4 года.',
    description: 'Классический speed dating с модератором и ночной выдачей мэтчей.',
    isAfterDark: true,
    afterDarkCategory: 'dating',
    afterDarkGlow: 'violet',
    dressCode: 'Smart casual',
    ageRange: '30–42',
    ratioLabel: '12 М / 12 Ж',
    consentRequired: false,
    rules: ['Только верифицированные', 'Анкеты заранее', 'Результаты после полуночи'],
    capacity: 24,
    isCalm: false,
    isNewcomers: false,
    isDate: true,
    hostId: 'user-anya',
  },
  {
    id: 'ad6',
    title: 'Naked Yoga · Female only',
    emoji: '🧘‍♀️',
    startsAt: new Date('2026-04-27T08:00:00.000Z'),
    durationMinutes: 90,
    place: 'Арбат',
    distanceKm: 1.8,
    latitude: 55.7495,
    longitude: 37.5925,
    vibe: 'Мягкий свет, медитативная практика, body acceptance',
    tone: 'sage',
    joinMode: 'request',
    lifestyle: 'zozh',
    priceMode: 'from',
    priceAmountFrom: 3000,
    accessMode: 'request',
    genderMode: 'female',
    visibilityMode: 'friends',
    hostNote: 'Безопасное пространство. Преподаю 6 лет.',
    description: 'Часовая практика в женском кругу. Принятие тела, дыхание и мягкая работа.',
    isAfterDark: true,
    afterDarkCategory: 'wellness',
    afterDarkGlow: 'cyan',
    dressCode: 'Optional',
    ageRange: '25–45',
    ratioLabel: 'Female only',
    consentRequired: true,
    rules: ['Только для женщин', 'Сертифицированная преподавательница', 'Полная конфиденциальность'],
    capacity: 10,
    isCalm: true,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-liza',
  },
  {
    id: 'ad7',
    title: 'Munch · Знакомство сообщества',
    emoji: '🖤',
    startsAt: new Date('2026-04-25T16:00:00.000Z'),
    durationMinutes: 150,
    place: '—',
    distanceKm: 4.5,
    latitude: 55.7732,
    longitude: 37.6801,
    vibe: 'Дружеская встреча в кафе, знакомимся и говорим без практик',
    tone: 'warm',
    joinMode: 'request',
    lifestyle: 'neutral',
    priceMode: 'free',
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Помогаю новичкам адаптироваться без давления.',
    description: 'Munch это знакомство сообщества за столом в обычном кафе. Без практик и без давления.',
    isAfterDark: true,
    afterDarkCategory: 'kink',
    afterDarkGlow: 'gold',
    dressCode: 'Vanilla',
    ageRange: '25–45',
    ratioLabel: 'Mixed',
    consentRequired: true,
    rules: [
      'Только для прошедших ручную модерацию',
      'Vanilla dress code',
      'Согласие это база',
      'Никакой съёмки и давления',
    ],
    capacity: 20,
    isCalm: true,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-oleg',
  },
  {
    id: 'ad8',
    title: 'Dress Code Night · Fetish Friendly',
    emoji: '🦋',
    startsAt: new Date('2026-04-26T19:30:00.000Z'),
    durationMinutes: 300,
    place: '—',
    distanceKm: 6.2,
    latitude: 55.7363,
    longitude: 37.5165,
    vibe: 'Закрытая вечеринка с жёстким дресс-кодом',
    tone: 'evening',
    joinMode: 'request',
    lifestyle: 'anti',
    priceMode: 'from',
    priceAmountFrom: 5000,
    accessMode: 'request',
    genderMode: 'all',
    visibilityMode: 'friends',
    hostNote: 'Безопасность и этика это первое.',
    description: 'Закрытая fetish-friendly вечеринка с awareness team и жёстким входным фильтром.',
    isAfterDark: true,
    afterDarkCategory: 'kink',
    afterDarkGlow: 'magenta',
    dressCode: 'Fetish / latex / lingerie / black',
    ageRange: '25–45',
    ratioLabel: 'Mixed',
    consentRequired: true,
    rules: [
      'Apply через анкету и фото',
      'Дресс-код проверяется на входе',
      'Consent culture без исключений',
      'Полный no-phone policy',
    ],
    capacity: 60,
    isCalm: false,
    isNewcomers: false,
    isDate: false,
    hostId: 'user-sonya',
  },
];

export const seededPosters: Array<{
  id: string;
  city: string;
  category:
    | 'concert'
    | 'sport'
    | 'exhibition'
    | 'theatre'
    | 'standup'
    | 'festival'
    | 'cinema';
  title: string;
  emoji: string;
  startsAt: Date;
  dateLabel: string;
  timeLabel: string;
  venue: string;
  address: string;
  distanceKm: number;
  priceFrom: number;
  ticketUrl: string;
  provider: string;
  tone: 'warm' | 'evening' | 'sage';
  tags: string[];
  description: string;
  isFeatured: boolean;
}> = [
  {
    id: 'ps1',
    city: 'Москва',
    category: 'concert',
    title: 'Молчат Дома · большой концерт',
    emoji: '🎸',
    startsAt: new Date('2026-04-26T20:00:00.000Z'),
    dateLabel: 'Сб, 26 апр',
    timeLabel: '20:00',
    venue: 'Adrenaline Stadium',
    address: 'Ленинградское ш. 80',
    distanceKm: 4.2,
    priceFrom: 3500,
    ticketUrl: 'https://afisha.yandex.ru',
    provider: 'Яндекс Афиша',
    tone: 'evening',
    tags: ['пост-панк', '18+', 'танцпол'],
    description: 'Юбилейный тур группы. Новый альбом и старые хиты.',
    isFeatured: true,
  },
  {
    id: 'ps2',
    city: 'Москва',
    category: 'sport',
    title: 'ЦСКА — Спартак · дерби',
    emoji: '⚽',
    startsAt: new Date('2026-04-27T19:00:00.000Z'),
    dateLabel: 'Вс, 27 апр',
    timeLabel: '19:00',
    venue: 'ВЭБ Арена',
    address: '3-я Песчаная ул. 2',
    distanceKm: 8.1,
    priceFrom: 1200,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'warm',
    tags: ['футбол', 'РПЛ', 'семейный сектор'],
    description: 'Главное московское дерби сезона. Атмосфера и фанатские перформансы.',
    isFeatured: true,
  },
  {
    id: 'ps3',
    city: 'Москва',
    category: 'exhibition',
    title: 'Кандинский. Контрапункт',
    emoji: '🎨',
    startsAt: new Date('2026-04-22T11:00:00.000Z'),
    dateLabel: 'Каждый день',
    timeLabel: '11:00–22:00',
    venue: 'Третьяковка на Крымском',
    address: 'Крымский Вал 10',
    distanceKm: 3.4,
    priceFrom: 800,
    ticketUrl: 'https://tretyakov.ru',
    provider: 'Третьяковка',
    tone: 'sage',
    tags: ['живопись', 'до 31 мая'],
    description: 'Большая ретроспектива с архивными работами и звуковой инсталляцией.',
    isFeatured: true,
  },
  {
    id: 'ps4',
    city: 'Москва',
    category: 'standup',
    title: 'Женский стендап · новые имена',
    emoji: '🎤',
    startsAt: new Date('2026-04-25T20:30:00.000Z'),
    dateLabel: 'Пт, 25 апр',
    timeLabel: '20:30',
    venue: 'StandUp Club #1',
    address: 'Новый Арбат 21',
    distanceKm: 2.7,
    priceFrom: 1500,
    ticketUrl: 'https://standupstore.ru',
    provider: 'StandUp Store',
    tone: 'warm',
    tags: ['юмор', '18+'],
    description: 'Вечер новых комиков с плотным лайнапом и камерной посадкой.',
    isFeatured: true,
  },
  {
    id: 'ps5',
    city: 'Москва',
    category: 'theatre',
    title: 'Гамлет',
    emoji: '🎭',
    startsAt: new Date('2026-04-24T19:00:00.000Z'),
    dateLabel: 'Чт, 24 апр',
    timeLabel: '19:00',
    venue: 'Театр на Бронной',
    address: 'Малая Бронная 4',
    distanceKm: 2.9,
    priceFrom: 2200,
    ticketUrl: 'https://teatrnabronnoy.ru',
    provider: 'Театр на Бронной',
    tone: 'evening',
    tags: ['драма', 'классика'],
    description: 'Современное прочтение Шекспира с минималистичной сценографией.',
    isFeatured: true,
  },
  {
    id: 'ps6',
    city: 'Москва',
    category: 'festival',
    title: 'Geek Picnic',
    emoji: '🎡',
    startsAt: new Date('2026-05-03T12:00:00.000Z'),
    dateLabel: 'Сб, 3 мая',
    timeLabel: '12:00',
    venue: 'Парк Горького',
    address: 'Крымский Вал 9',
    distanceKm: 3.5,
    priceFrom: 1800,
    ticketUrl: 'https://geek-picnic.me',
    provider: 'Geek Picnic',
    tone: 'sage',
    tags: ['технологии', 'лекторий', 'open-air'],
    description: 'Городской фестиваль технологий, науки и интерактивных зон.',
    isFeatured: false,
  },
  {
    id: 'ps7',
    city: 'Москва',
    category: 'concert',
    title: 'Хадн Дадн',
    emoji: '🎶',
    startsAt: new Date('2026-04-28T20:00:00.000Z'),
    dateLabel: 'Пн, 28 апр',
    timeLabel: '20:00',
    venue: '16 Тонн',
    address: 'Пресненский Вал 6с1',
    distanceKm: 4.8,
    priceFrom: 2500,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'evening',
    tags: ['инди', 'концерт'],
    description: 'Тихий, нервный и очень городской концерт для своих.',
    isFeatured: false,
  },
  {
    id: 'ps8',
    city: 'Москва',
    category: 'cinema',
    title: 'Ночь короткого метра',
    emoji: '🎬',
    startsAt: new Date('2026-04-26T22:00:00.000Z'),
    dateLabel: 'Сб, 26 апр',
    timeLabel: '22:00',
    venue: 'Каро Октябрь',
    address: 'Новый Арбат 24',
    distanceKm: 2.2,
    priceFrom: 900,
    ticketUrl: 'https://karofilm.ru',
    provider: 'КАРО',
    tone: 'warm',
    tags: ['короткий метр', 'ночной показ'],
    description: 'Сборник короткометражек с обсуждением после сеанса.',
    isFeatured: false,
  },
  {
    id: 'ps9',
    city: 'Москва',
    category: 'exhibition',
    title: 'Новая графика',
    emoji: '🖼️',
    startsAt: new Date('2026-04-23T12:00:00.000Z'),
    dateLabel: 'Каждый день',
    timeLabel: '12:00–21:00',
    venue: 'Гараж',
    address: 'Крымский Вал 9с32',
    distanceKm: 3.5,
    priceFrom: 700,
    ticketUrl: 'https://garagemca.org',
    provider: 'Garage',
    tone: 'sage',
    tags: ['графика', 'современное искусство'],
    description: 'Групповая выставка молодых художников с акцентом на печатные техники.',
    isFeatured: false,
  },
  {
    id: 'ps10',
    city: 'Москва',
    category: 'festival',
    title: 'Фестиваль кофе и винила',
    emoji: '☕',
    startsAt: new Date('2026-04-27T13:00:00.000Z'),
    dateLabel: 'Вс, 27 апр',
    timeLabel: '13:00',
    venue: 'Хлебозавод',
    address: 'Новодмитровская 1',
    distanceKm: 6.0,
    priceFrom: 0,
    ticketUrl: 'https://afisha.ru',
    provider: 'Афиша',
    tone: 'warm',
    tags: ['кофе', 'маркет', 'бесплатно'],
    description: 'Обжарщики, виниловые сеты, маркет локальных брендов и дегустации.',
    isFeatured: false,
  },
  {
    id: 'ps11',
    city: 'Москва',
    category: 'sport',
    title: 'Ночной забег по центру',
    emoji: '🏃',
    startsAt: new Date('2026-04-29T21:00:00.000Z'),
    dateLabel: 'Вт, 29 апр',
    timeLabel: '21:00',
    venue: 'Лужники',
    address: 'Лужнецкая наб. 24',
    distanceKm: 7.2,
    priceFrom: 2000,
    ticketUrl: 'https://kassir.ru',
    provider: 'Kassir',
    tone: 'sage',
    tags: ['бег', '10 км', 'ночь'],
    description: 'Городской массовый забег с вечерним светом и музыкой на маршруте.',
    isFeatured: false,
  },
  {
    id: 'ps12',
    city: 'Москва',
    category: 'theatre',
    title: 'Лебединое озеро',
    emoji: '🩰',
    startsAt: new Date('2026-04-30T19:00:00.000Z'),
    dateLabel: 'Ср, 30 апр',
    timeLabel: '19:00',
    venue: 'Большой театр',
    address: 'Театральная пл. 1',
    distanceKm: 1.9,
    priceFrom: 4500,
    ticketUrl: 'https://bolshoi.ru',
    provider: 'Большой театр',
    tone: 'evening',
    tags: ['балет', 'классика'],
    description: 'Классическая постановка в исторической сцене Большого театра.',
    isFeatured: false,
  },
];

export const seededEveningRoutes: Array<{
  id: string;
  title: string;
  vibe: string;
  blurb: string;
  totalPriceFrom: number;
  totalSavings: number;
  durationLabel: string;
  area: string;
  goal: string;
  mood: string;
  budget: string;
  format: string;
  premium?: boolean;
  recommendedFor?: string | null;
  hostsCount: number;
  chatId: string;
  steps: Array<{
    id: string;
    timeLabel: string;
    endTimeLabel?: string | null;
    kind: string;
    title: string;
    venue: string;
    address: string;
    emoji: string;
    distanceLabel: string;
    walkMin?: number | null;
    perk?: string | null;
    perkShort?: string | null;
    ticketPrice?: number | null;
    ticketCommission?: number | null;
    sponsored?: boolean;
    premium?: boolean;
    partnerId?: string | null;
    description?: string | null;
    vibeTag?: string | null;
    lat: number;
    lng: number;
  }>;
}> = [
  {
    id: 'r-cozy-circle',
    title: 'Теплый круг на Покровке',
    vibe: 'Камерный вечер с новыми людьми',
    blurb: 'Аперитив, легкий стендап и долгий разговор в кофейне',
    totalPriceFrom: 1400,
    totalSavings: 650,
    durationLabel: '19:00 - 00:30',
    area: 'Чистые пруды -> Покровка',
    goal: 'newfriends',
    mood: 'chill',
    budget: 'mid',
    format: 'mixed',
    recommendedFor: 'Для тех, кто впервые',
    hostsCount: 8,
    chatId: 'evening-chat-r-cozy-circle',
    steps: [
      {
        id: 's1-1',
        timeLabel: '19:00',
        endTimeLabel: '20:15',
        kind: 'bar',
        title: 'Аперитив в Brix Wine',
        venue: 'Brix Wine',
        address: 'Покровка 12',
        emoji: '🍇',
        distanceLabel: '1.2 км',
        walkMin: 14,
        perk: '-15% на бокалы и бутылку для группы',
        perkShort: '-15%',
        partnerId: 'p-brix',
        vibeTag: 'Уютно',
        description: 'Знакомство за бокалом без формальностей',
        lat: 0.42,
        lng: 0.38,
      },
      {
        id: 's1-2',
        timeLabel: '20:30',
        endTimeLabel: '22:00',
        kind: 'show',
        title: 'Открытый микрофон Standup Store',
        venue: 'Standup Store',
        address: 'Бол. Дмитровка 32',
        emoji: '🎤',
        distanceLabel: '2.1 км',
        walkMin: 6,
        ticketPrice: 800,
        ticketCommission: 80,
        vibeTag: 'Смех',
        description: 'Молодые комики, короткие сеты, легкая атмосфера',
        lat: 0.55,
        lng: 0.32,
      },
      {
        id: 's1-3',
        timeLabel: '22:30',
        endTimeLabel: '00:30',
        kind: 'afterparty',
        title: 'After-chat в Кафе Заря',
        venue: 'Кафе Заря',
        address: 'Хохловский пер. 7',
        emoji: '☕',
        distanceLabel: '0.9 км',
        walkMin: 9,
        perk: 'Второй кофе в подарок, стол держим до 01:00',
        perkShort: '1+1',
        partnerId: 'p-zarya',
        vibeTag: 'Тепло',
        description: 'Разбираем вечер, обмениваемся контактами',
        lat: 0.44,
        lng: 0.42,
      },
      {
        id: 's1-4',
        timeLabel: 'Завтра',
        kind: 'followup',
        title: 'Follow-up с теми, кто понравился',
        venue: 'Frendly чат',
        address: 'В приложении',
        emoji: '💬',
        distanceLabel: '-',
        vibeTag: 'Связь',
        description: 'Утром Frendly предложит написать тем, кто был на маршруте',
        lat: 0.5,
        lng: 0.5,
      },
    ],
  },
  {
    id: 'r-date-noir',
    title: 'Свидание Noir',
    vibe: 'Вечер для двоих, кино и поздний бар',
    blurb: 'Камерный показ, прогулка и финал на крыше',
    totalPriceFrom: 2400,
    totalSavings: 900,
    durationLabel: '20:00 - 01:00',
    area: 'Парк Горького -> Берсеневская',
    goal: 'date',
    mood: 'date',
    budget: 'high',
    format: 'show',
    premium: true,
    recommendedFor: 'Идеально для второго свидания',
    hostsCount: 3,
    chatId: 'evening-chat-r-date-noir',
    steps: [
      {
        id: 's2-1',
        timeLabel: '20:00',
        endTimeLabel: '21:45',
        kind: 'show',
        title: 'Авторское кино в Garage Screen',
        venue: 'Garage Screen',
        address: 'Парк Горького',
        emoji: '🎬',
        distanceLabel: '3.5 км',
        walkMin: 12,
        ticketPrice: 600,
        ticketCommission: 60,
        perk: '-15% билет по коду Frendly',
        perkShort: '-15%',
        partnerId: 'p-kino',
        vibeTag: 'Кинематично',
        description: 'Авторский показ с обсуждением в фойе',
        lat: 0.32,
        lng: 0.62,
      },
      {
        id: 's2-2',
        timeLabel: '22:00',
        endTimeLabel: '23:00',
        kind: 'dinner',
        title: 'Ужин в Tilda Bistro',
        venue: 'Tilda Bistro',
        address: 'Спиридоньевский 10А',
        emoji: '🍝',
        distanceLabel: '1.4 км',
        walkMin: 18,
        perk: 'Комплимент шефа на пару',
        perkShort: 'Комплимент',
        partnerId: 'p-tilda',
        sponsored: true,
        vibeTag: 'Гастро',
        description: 'Маленький бистро на двоих, теплый свет',
        lat: 0.48,
        lng: 0.46,
      },
      {
        id: 's2-3',
        timeLabel: '23:30',
        endTimeLabel: '01:00',
        kind: 'bar',
        title: 'Финал на крыше Стрелка',
        venue: 'Стрелка',
        address: 'Берсеневская наб. 14',
        emoji: '🍸',
        distanceLabel: '2.8 км',
        walkMin: 8,
        perk: 'Welcome-коктейль на пару',
        perkShort: 'Welcome',
        partnerId: 'p-strelka',
        vibeTag: 'Виды',
        description: 'Огни города, тихая музыка, поздний разговор',
        lat: 0.38,
        lng: 0.55,
      },
    ],
  },
  {
    id: 'r-wild-night',
    title: 'Большой вечер в центре',
    vibe: 'Активная компания и танцы до утра',
    blurb: 'Бар, концерт и клуб с fast-track для группы',
    totalPriceFrom: 2800,
    totalSavings: 1200,
    durationLabel: '20:00 - 04:00',
    area: 'Тверская -> Курская',
    goal: 'company',
    mood: 'wild',
    budget: 'high',
    format: 'mixed',
    hostsCount: 14,
    chatId: 'evening-chat-r-wild-night',
    steps: [
      {
        id: 's3-1',
        timeLabel: '20:00',
        endTimeLabel: '21:30',
        kind: 'bar',
        title: 'Старт в Noor Bar',
        venue: 'Noor Bar',
        address: 'Тверская 23',
        emoji: '🥃',
        distanceLabel: '2.4 км',
        walkMin: 10,
        perk: '-10% на весь чек до 22:00',
        perkShort: '-10%',
        partnerId: 'p-noor',
        vibeTag: 'Старт',
        lat: 0.5,
        lng: 0.3,
      },
      {
        id: 's3-2',
        timeLabel: '22:00',
        endTimeLabel: '23:30',
        kind: 'show',
        title: 'Концерт в Arma17',
        venue: 'Arma17',
        address: 'Нижний Сусальный 5',
        emoji: '🎧',
        distanceLabel: '3.2 км',
        walkMin: 14,
        ticketPrice: 1200,
        ticketCommission: 120,
        perk: '-20% early bird по промо',
        perkShort: '-20%',
        partnerId: 'p-arma',
        vibeTag: 'Лайв',
        lat: 0.62,
        lng: 0.4,
      },
      {
        id: 's3-3',
        timeLabel: '00:00',
        endTimeLabel: '04:00',
        kind: 'afterparty',
        title: 'Afterparty в Mutabor',
        venue: 'Mutabor',
        address: 'Шарикоподшипниковская 13',
        emoji: '🪩',
        distanceLabel: '5.1 км',
        walkMin: 20,
        perk: 'Fast-track вход для группы 4+',
        perkShort: 'Fast-track',
        partnerId: 'p-mutabor',
        sponsored: true,
        vibeTag: 'Танцы',
        lat: 0.72,
        lng: 0.55,
      },
    ],
  },
  {
    id: 'r-quiet-soul',
    title: 'Тихий вечер для себя',
    vibe: 'Отдых, баня и долгая прогулка',
    blurb: 'Wellness, легкий ужин и медленный финал',
    totalPriceFrom: 3200,
    totalSavings: 1100,
    durationLabel: '18:30 - 23:00',
    area: 'Цветной -> Патриаршие',
    goal: 'quiet',
    mood: 'chill',
    budget: 'mid',
    format: 'active',
    premium: true,
    recommendedFor: 'Перезагрузиться после недели',
    hostsCount: 5,
    chatId: 'evening-chat-r-quiet-soul',
    steps: [
      {
        id: 's4-1',
        timeLabel: '18:30',
        endTimeLabel: '20:00',
        kind: 'wellness',
        title: 'Парная сессия Esthetic Spa',
        venue: 'Esthetic Spa',
        address: 'Цветной бульвар 11',
        emoji: '💆',
        distanceLabel: '1.7 км',
        walkMin: 8,
        perk: '-25% на парный массаж',
        perkShort: '-25%',
        partnerId: 'p-spa',
        vibeTag: 'Тишина',
        lat: 0.46,
        lng: 0.34,
      },
      {
        id: 's4-2',
        timeLabel: '20:30',
        endTimeLabel: '22:00',
        kind: 'dinner',
        title: 'Ужин на Патриках',
        venue: 'Tilda Bistro',
        address: 'Спиридоньевский 10А',
        emoji: '🍝',
        distanceLabel: '1.4 км',
        walkMin: 12,
        perk: 'Комплимент шефа',
        perkShort: 'Комплимент',
        partnerId: 'p-tilda',
        vibeTag: 'Гастро',
        lat: 0.48,
        lng: 0.46,
      },
      {
        id: 's4-3',
        timeLabel: '22:30',
        endTimeLabel: '23:00',
        kind: 'afterparty',
        title: 'Прогулка вокруг прудов',
        venue: 'Патриаршие пруды',
        address: 'Малая Бронная',
        emoji: '🌙',
        distanceLabel: '0.4 км',
        walkMin: 5,
        vibeTag: 'Покой',
        lat: 0.5,
        lng: 0.5,
      },
    ],
  },
  {
    id: 'r-afterdark',
    title: 'After Dark, приватный круг',
    vibe: '18+ закрытое событие и медленный финал',
    blurb: 'Закрытая сессия, бар-перформанс, утренний хаммам',
    totalPriceFrom: 4500,
    totalSavings: 1500,
    durationLabel: '22:00 - 06:00',
    area: 'Красный Октябрь -> Неглинная',
    goal: 'afterdark',
    mood: 'afterdark',
    budget: 'high',
    format: 'mixed',
    premium: true,
    recommendedFor: 'Только Frendly+ и After Dark',
    hostsCount: 2,
    chatId: 'evening-chat-r-afterdark',
    steps: [
      {
        id: 's5-1',
        timeLabel: '22:00',
        endTimeLabel: '23:30',
        kind: 'show',
        title: 'Закрытая сессия 18+',
        venue: 'Скрыто до подтверждения',
        address: 'Адрес откроется за 4 ч',
        emoji: '🕯️',
        distanceLabel: '-',
        vibeTag: 'Приватно',
        lat: 0.4,
        lng: 0.6,
      },
      {
        id: 's5-2',
        timeLabel: '00:00',
        endTimeLabel: '02:30',
        kind: 'bar',
        title: 'Бар-перформанс Стрелка Late',
        venue: 'Стрелка',
        address: 'Берсеневская наб. 14',
        emoji: '🍸',
        distanceLabel: '2.8 км',
        perk: 'Welcome-коктейль для пары',
        perkShort: 'Welcome',
        partnerId: 'p-strelka',
        vibeTag: 'Атмосфера',
        lat: 0.38,
        lng: 0.55,
      },
      {
        id: 's5-3',
        timeLabel: '04:00',
        endTimeLabel: '06:00',
        kind: 'wellness',
        title: 'Утренний хаммам',
        venue: 'Сандуны Lab',
        address: 'Неглинная 14',
        emoji: '🧖',
        distanceLabel: '2.0 км',
        perk: 'Парение в подарок',
        perkShort: 'В подарок',
        partnerId: 'p-banya',
        vibeTag: 'Перезагрузка',
        lat: 0.5,
        lng: 0.4,
      },
    ],
  },
];
