export const seededUsers: Array<{
  id: string;
  displayName: string;
  verified: boolean;
  online: boolean;
  age: number;
  city: string;
  area: string;
  bio: string;
  vibe: string;
  rating: number;
  meetupCount: number;
  avatarUrl: string;
  intent: string;
  interests: string[];
}> = [
  {
    id: 'user-me',
    displayName: 'Никита М',
    verified: true,
    online: true,
    age: 28,
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Дизайнер. Люблю долгие прогулки и тихие бары. Ищу людей, с которыми можно собраться без долгого планирования.',
    vibe: 'Спокойно',
    rating: 4.8,
    meetupCount: 12,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Nikita',
    intent: 'both',
    interests: ['Кофе', 'Бары', 'Настолки', 'Кино', 'Книги', 'Велик'],
  },
  {
    id: 'user-anya',
    displayName: 'Аня К',
    verified: true,
    online: true,
    age: 27,
    city: 'Москва',
    area: 'Чистые пруды',
    bio: 'Люблю камерные вечера и хорошие бары.',
    vibe: 'Спокойно',
    rating: 4.9,
    meetupCount: 23,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Anya',
    intent: 'dating',
    interests: ['Кофе', 'Настолки', 'Бары'],
  },
  {
    id: 'user-mark',
    displayName: 'Марк С',
    verified: true,
    online: true,
    age: 30,
    city: 'Москва',
    area: 'Патрики',
    bio: 'Кино, вино, быстрые встречи без формальностей.',
    vibe: 'Шумно',
    rating: 4.7,
    meetupCount: 18,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Mark',
    intent: 'friendship',
    interests: ['Бары', 'Кино'],
  },
  {
    id: 'user-liza',
    displayName: 'Лиза П',
    verified: true,
    online: false,
    age: 25,
    city: 'Москва',
    area: 'Хамовники',
    bio: 'Спокойные бары и йога по утрам.',
    vibe: 'Спокойно',
    rating: 4.6,
    meetupCount: 8,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Liza',
    intent: 'both',
    interests: ['Йога', 'Книги'],
  },
  {
    id: 'user-dima',
    displayName: 'Дима Р',
    verified: false,
    online: false,
    age: 29,
    city: 'Москва',
    area: 'Сокол',
    bio: 'Бегаю по вечерам и люблю спонтанные планы.',
    vibe: 'Активно',
    rating: 4.2,
    meetupCount: 6,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Dima',
    intent: 'friendship',
    interests: ['Бег', 'Велик'],
  },
  {
    id: 'user-sonya',
    displayName: 'Соня М',
    verified: true,
    online: true,
    age: 26,
    city: 'Москва',
    area: 'Замоскворечье',
    bio: 'Театр, готовка и долгие прогулки.',
    vibe: 'Спокойно',
    rating: 4.5,
    meetupCount: 9,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Sonya',
    intent: 'both',
    interests: ['Театр', 'Готовка'],
  },
  {
    id: 'user-oleg',
    displayName: 'Олег К',
    verified: true,
    online: false,
    age: 31,
    city: 'Москва',
    area: 'Центр',
    bio: 'Музыка, бары, новые компании.',
    vibe: 'Шумно',
    rating: 4.4,
    meetupCount: 10,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Oleg',
    intent: 'friendship',
    interests: ['Музыка', 'Бары'],
  },
  {
    id: 'user-katya',
    displayName: 'Катя',
    verified: true,
    online: false,
    age: 27,
    city: 'Москва',
    area: 'Центр',
    bio: 'Настолки и поздний кофе.',
    vibe: 'Уютно',
    rating: 4.5,
    meetupCount: 7,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Katya',
    intent: 'friendship',
    interests: ['Настолки', 'Кофе'],
  },
  {
    id: 'user-pasha',
    displayName: 'Паша',
    verified: true,
    online: false,
    age: 28,
    city: 'Москва',
    area: 'Центр',
    bio: 'Несу настолки, если собирается компания.',
    vibe: 'Уютно',
    rating: 4.4,
    meetupCount: 11,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Pasha',
    intent: 'friendship',
    interests: ['Настолки', 'Кофе'],
  },
  {
    id: 'user-ira',
    displayName: 'Ира',
    verified: true,
    online: false,
    age: 27,
    city: 'Москва',
    area: 'Центр',
    bio: 'Люблю уютные вечера.',
    vibe: 'Уютно',
    rating: 4.3,
    meetupCount: 5,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Ira',
    intent: 'both',
    interests: ['Книги', 'Настолки'],
  },
  {
    id: 'user-timur',
    displayName: 'Тимур',
    verified: true,
    online: false,
    age: 29,
    city: 'Москва',
    area: 'Центр',
    bio: 'Редко пишу, но всегда прихожу.',
    vibe: 'Уютно',
    rating: 4.3,
    meetupCount: 4,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Timur',
    intent: 'friendship',
    interests: ['Кино', 'Настолки'],
  },
  {
    id: 'user-lena',
    displayName: 'Лена',
    verified: true,
    online: false,
    age: 26,
    city: 'Москва',
    area: 'Центр',
    bio: 'Ищу спокойные встречи и хороший кофе.',
    vibe: 'Уютно',
    rating: 4.6,
    meetupCount: 6,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Lena',
    intent: 'both',
    interests: ['Кофе', 'Настолки'],
  },
  {
    id: 'user-masha',
    displayName: 'Маша',
    verified: true,
    online: false,
    age: 29,
    city: 'Москва',
    area: 'Парк Горького',
    bio: 'Люблю кино под открытым небом.',
    vibe: 'Свидание',
    rating: 4.7,
    meetupCount: 12,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Masha',
    intent: 'dating',
    interests: ['Кино', 'Музыка'],
  },
  {
    id: 'user-artem',
    displayName: 'Артём',
    verified: true,
    online: false,
    age: 31,
    city: 'Москва',
    area: 'Парк Горького',
    bio: 'Показываю хорошие фильмы и места.',
    vibe: 'Свидание',
    rating: 4.4,
    meetupCount: 10,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Artem',
    intent: 'dating',
    interests: ['Кино', 'Музыка'],
  },
  {
    id: 'user-yulia',
    displayName: 'Юля',
    verified: true,
    online: false,
    age: 28,
    city: 'Москва',
    area: 'Парк Горького',
    bio: 'Летние киносеансы и прогулки.',
    vibe: 'Свидание',
    rating: 4.5,
    meetupCount: 9,
    avatarUrl: 'https://api.dicebear.com/7.x/thumbs/svg?seed=Yulia',
    intent: 'dating',
    interests: ['Кино', 'Прогулки'],
  },
];

export const seededEvents: Array<{
  id: string;
  title: string;
  emoji: string;
  startsAt: Date;
  durationMinutes: number;
  place: string;
  distanceKm: number;
  vibe: string;
  tone: 'warm' | 'evening' | 'sage';
  joinMode?: 'open' | 'request';
  hostNote?: string;
  description: string;
  partnerName?: string;
  partnerOffer?: string;
  capacity: number;
  isCalm: boolean;
  isNewcomers: boolean;
  isDate: boolean;
  hostId: string;
}> = [
  {
    id: 'e1',
    title: 'Винный вечер на крыше',
    emoji: '🍷',
    startsAt: new Date('2026-04-18T20:00:00.000Z'),
    durationMinutes: 120,
    place: 'Brix Wine, Покровка 12',
    distanceKm: 1.2,
    vibe: 'Спокойно',
    tone: 'evening',
    joinMode: 'open',
    hostNote: 'Знакомимся за бокалом, без спешки.',
    description: 'Камерный вечер на крыше с винами от локального сомелье. Без программы и спешки, просто хороший разговор, виды на город и пара бокалов.',
    partnerName: 'Brix Wine',
    partnerOffer: '−15% на бокалы для участников',
    capacity: 10,
    isCalm: true,
    isNewcomers: true,
    isDate: true,
    hostId: 'user-anya',
  },
  {
    id: 'e2',
    title: 'Вечерняя пробежка по бульварам',
    emoji: '🌿',
    startsAt: new Date('2026-04-18T19:30:00.000Z'),
    durationMinutes: 90,
    place: 'Чистые пруды',
    distanceKm: 0.6,
    vibe: 'Активно',
    tone: 'sage',
    joinMode: 'open',
    description: 'Легкая пробежка по бульварам, без темпа на результат, просто двигаемся вместе.',
    capacity: 8,
    isCalm: false,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-dima',
  },
  {
    id: 'e3',
    title: 'Настолки и кофе',
    emoji: '♟️',
    startsAt: new Date('2026-04-18T19:00:00.000Z'),
    durationMinutes: 180,
    place: 'Кафе Заря, Хохловский',
    distanceKm: 0.9,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'open',
    description: 'Небольшая компания, кофе и настолки до закрытия. Можно прийти одному.',
    capacity: 12,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-pasha',
  },
  {
    id: 'e4',
    title: 'Кино под открытым небом',
    emoji: '🎬',
    startsAt: new Date('2026-04-19T21:00:00.000Z'),
    durationMinutes: 150,
    place: 'Парк Горького',
    distanceKm: 3.4,
    vibe: 'Свидание',
    tone: 'evening',
    joinMode: 'open',
    description: 'Летний киносеанс под открытым небом. Можно прийти с пледом и друзьями.',
    capacity: 30,
    isCalm: true,
    isNewcomers: false,
    isDate: true,
    hostId: 'user-masha',
  },
  {
    id: 'e5',
    title: 'Камерный ужин по заявкам',
    emoji: '🍝',
    startsAt: new Date('2026-04-19T18:30:00.000Z'),
    durationMinutes: 150,
    place: 'Солянка 5',
    distanceKm: 0.7,
    vibe: 'Уютно',
    tone: 'warm',
    joinMode: 'request',
    hostNote: 'Хочу собрать маленькую спокойную компанию.',
    description: 'Ужин в маленькой компании. Сначала заявка, потом подтверждение хостом.',
    capacity: 6,
    isCalm: true,
    isNewcomers: true,
    isDate: false,
    hostId: 'user-me',
  },
];
