/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SosRouteImport } from './routes/sos'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostersRouteImport } from './routes/posters'
import { Route as PerksRouteImport } from './routes/perks'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MemoryMapRouteImport } from './routes/memory-map'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MapRouteImport } from './routes/map'
import { Route as HostRouteImport } from './routes/host'
import { Route as GiveawaysRouteImport } from './routes/giveaways'
import { Route as EveningRouteImport } from './routes/evening'
import { Route as DatingRouteImport } from './routes/dating'
import { Route as CityRouteImport } from './routes/city'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AfterDarkRouteImport } from './routes/after-dark'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingsIndexRouteImport } from './routes/meetings.index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as AiBuilderIndexRouteImport } from './routes/ai-builder.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ProfileGalleryRouteImport } from './routes/profile.gallery'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as MeetingsNewRouteImport } from './routes/meetings.new'
import { Route as DatingFilterRouteImport } from './routes/dating.filter'
import { Route as CommunitiesNewRouteImport } from './routes/communities.new'
import { Route as CommunitiesIdRouteImport } from './routes/communities.$id'
import { Route as AuthTelegramRouteImport } from './routes/auth.telegram'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as AiBuilderResultRouteImport } from './routes/ai-builder.result'
import { Route as MeetingsMeetingIdIndexRouteImport } from './routes/meetings.$meetingId.index'
import { Route as MeetingsMeetingIdChatRouteImport } from './routes/meetings.$meetingId.chat'
import { Route as CommunitiesIdChatRouteImport } from './routes/communities.$id.chat'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostersRoute = PostersRouteImport.update({
  id: '/posters',
  path: '/posters',
  getParentRoute: () => rootRouteImport,
} as any)
const PerksRoute = PerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryMapRoute = MemoryMapRouteImport.update({
  id: '/memory-map',
  path: '/memory-map',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysRoute = GiveawaysRouteImport.update({
  id: '/giveaways',
  path: '/giveaways',
  getParentRoute: () => rootRouteImport,
} as any)
const EveningRoute = EveningRouteImport.update({
  id: '/evening',
  path: '/evening',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingRoute = DatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterDarkRoute = AfterDarkRouteImport.update({
  id: '/after-dark',
  path: '/after-dark',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsIndexRoute = MeetingsIndexRouteImport.update({
  id: '/meetings/',
  path: '/meetings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderIndexRoute = AiBuilderIndexRouteImport.update({
  id: '/ai-builder/',
  path: '/ai-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/$routeId',
  path: '/$routeId',
  getParentRoute: () => RoutesRoute,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileGalleryRoute = ProfileGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const MeetingsNewRoute = MeetingsNewRouteImport.update({
  id: '/meetings/new',
  path: '/meetings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingFilterRoute = DatingFilterRouteImport.update({
  id: '/filter',
  path: '/filter',
  getParentRoute: () => DatingRoute,
} as any)
const CommunitiesNewRoute = CommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdRoute = CommunitiesIdRouteImport.update({
  id: '/communities/$id',
  path: '/communities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTelegramRoute = AuthTelegramRouteImport.update({
  id: '/auth/telegram',
  path: '/auth/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/auth/phone',
  path: '/auth/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuilderResultRoute = AiBuilderResultRouteImport.update({
  id: '/ai-builder/result',
  path: '/ai-builder/result',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdIndexRoute = MeetingsMeetingIdIndexRouteImport.update({
  id: '/meetings/$meetingId/',
  path: '/meetings/$meetingId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsMeetingIdChatRoute = MeetingsMeetingIdChatRouteImport.update({
  id: '/meetings/$meetingId/chat',
  path: '/meetings/$meetingId/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIdChatRoute = CommunitiesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CommunitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/after-dark': typeof AfterDarkRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/dating': typeof DatingRouteWithChildren
  '/evening': typeof EveningRoute
  '/giveaways': typeof GiveawaysRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/memory-map': typeof MemoryMapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/perks': typeof PerksRoute
  '/posters': typeof PostersRoute
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/routes': typeof RoutesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sos': typeof SosRoute
  '/splash': typeof SplashRoute
  '/stories': typeof StoriesRoute
  '/streak': typeof StreakRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/ai-builder/result': typeof AiBuilderResultRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/dating/filter': typeof DatingFilterRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/gallery': typeof ProfileGalleryRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/ai-builder/': typeof AiBuilderIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/communities/$id/chat': typeof CommunitiesIdChatRoute
  '/meetings/$meetingId/chat': typeof MeetingsMeetingIdChatRoute
  '/meetings/$meetingId/': typeof MeetingsMeetingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/after-dark': typeof AfterDarkRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/dating': typeof DatingRouteWithChildren
  '/evening': typeof EveningRoute
  '/giveaways': typeof GiveawaysRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/memory-map': typeof MemoryMapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/perks': typeof PerksRoute
  '/posters': typeof PostersRoute
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/routes': typeof RoutesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sos': typeof SosRoute
  '/splash': typeof SplashRoute
  '/stories': typeof StoriesRoute
  '/streak': typeof StreakRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/ai-builder/result': typeof AiBuilderResultRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/dating/filter': typeof DatingFilterRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/gallery': typeof ProfileGalleryRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/ai-builder': typeof AiBuilderIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/meetings': typeof MeetingsIndexRoute
  '/communities/$id/chat': typeof CommunitiesIdChatRoute
  '/meetings/$meetingId/chat': typeof MeetingsMeetingIdChatRoute
  '/meetings/$meetingId': typeof MeetingsMeetingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/after-dark': typeof AfterDarkRoute
  '/chats': typeof ChatsRoute
  '/city': typeof CityRoute
  '/dating': typeof DatingRouteWithChildren
  '/evening': typeof EveningRoute
  '/giveaways': typeof GiveawaysRoute
  '/host': typeof HostRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/memory-map': typeof MemoryMapRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/perks': typeof PerksRoute
  '/posters': typeof PostersRoute
  '/profile': typeof ProfileRouteWithChildren
  '/report': typeof ReportRoute
  '/routes': typeof RoutesRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/sos': typeof SosRoute
  '/splash': typeof SplashRoute
  '/stories': typeof StoriesRoute
  '/streak': typeof StreakRoute
  '/verify': typeof VerifyRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/ai-builder/result': typeof AiBuilderResultRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/telegram': typeof AuthTelegramRoute
  '/communities/$id': typeof CommunitiesIdRouteWithChildren
  '/communities/new': typeof CommunitiesNewRoute
  '/dating/filter': typeof DatingFilterRoute
  '/meetings/new': typeof MeetingsNewRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/gallery': typeof ProfileGalleryRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/u/$userId': typeof UUserIdRoute
  '/ai-builder/': typeof AiBuilderIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/meetings/': typeof MeetingsIndexRoute
  '/communities/$id/chat': typeof CommunitiesIdChatRoute
  '/meetings/$meetingId/chat': typeof MeetingsMeetingIdChatRoute
  '/meetings/$meetingId/': typeof MeetingsMeetingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/after-dark'
    | '/chats'
    | '/city'
    | '/dating'
    | '/evening'
    | '/giveaways'
    | '/host'
    | '/map'
    | '/match'
    | '/memory-map'
    | '/notifications'
    | '/onboarding'
    | '/paywall'
    | '/perks'
    | '/posters'
    | '/profile'
    | '/report'
    | '/routes'
    | '/search'
    | '/settings'
    | '/share'
    | '/sos'
    | '/splash'
    | '/stories'
    | '/streak'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/ai-builder/result'
    | '/auth/phone'
    | '/auth/telegram'
    | '/communities/$id'
    | '/communities/new'
    | '/dating/filter'
    | '/meetings/new'
    | '/profile/edit'
    | '/profile/gallery'
    | '/profile/history'
    | '/routes/$routeId'
    | '/u/$userId'
    | '/ai-builder/'
    | '/communities/'
    | '/meetings/'
    | '/communities/$id/chat'
    | '/meetings/$meetingId/chat'
    | '/meetings/$meetingId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/after-dark'
    | '/chats'
    | '/city'
    | '/dating'
    | '/evening'
    | '/giveaways'
    | '/host'
    | '/map'
    | '/match'
    | '/memory-map'
    | '/notifications'
    | '/onboarding'
    | '/paywall'
    | '/perks'
    | '/posters'
    | '/profile'
    | '/report'
    | '/routes'
    | '/search'
    | '/settings'
    | '/share'
    | '/sos'
    | '/splash'
    | '/stories'
    | '/streak'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/ai-builder/result'
    | '/auth/phone'
    | '/auth/telegram'
    | '/communities/$id'
    | '/communities/new'
    | '/dating/filter'
    | '/meetings/new'
    | '/profile/edit'
    | '/profile/gallery'
    | '/profile/history'
    | '/routes/$routeId'
    | '/u/$userId'
    | '/ai-builder'
    | '/communities'
    | '/meetings'
    | '/communities/$id/chat'
    | '/meetings/$meetingId/chat'
    | '/meetings/$meetingId'
  id:
    | '__root__'
    | '/'
    | '/after-dark'
    | '/chats'
    | '/city'
    | '/dating'
    | '/evening'
    | '/giveaways'
    | '/host'
    | '/map'
    | '/match'
    | '/memory-map'
    | '/notifications'
    | '/onboarding'
    | '/paywall'
    | '/perks'
    | '/posters'
    | '/profile'
    | '/report'
    | '/routes'
    | '/search'
    | '/settings'
    | '/share'
    | '/sos'
    | '/splash'
    | '/stories'
    | '/streak'
    | '/verify'
    | '/wallet'
    | '/welcome'
    | '/ai-builder/result'
    | '/auth/phone'
    | '/auth/telegram'
    | '/communities/$id'
    | '/communities/new'
    | '/dating/filter'
    | '/meetings/new'
    | '/profile/edit'
    | '/profile/gallery'
    | '/profile/history'
    | '/routes/$routeId'
    | '/u/$userId'
    | '/ai-builder/'
    | '/communities/'
    | '/meetings/'
    | '/communities/$id/chat'
    | '/meetings/$meetingId/chat'
    | '/meetings/$meetingId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfterDarkRoute: typeof AfterDarkRoute
  ChatsRoute: typeof ChatsRoute
  CityRoute: typeof CityRoute
  DatingRoute: typeof DatingRouteWithChildren
  EveningRoute: typeof EveningRoute
  GiveawaysRoute: typeof GiveawaysRoute
  HostRoute: typeof HostRoute
  MapRoute: typeof MapRoute
  MatchRoute: typeof MatchRoute
  MemoryMapRoute: typeof MemoryMapRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  PerksRoute: typeof PerksRoute
  PostersRoute: typeof PostersRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReportRoute: typeof ReportRoute
  RoutesRoute: typeof RoutesRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  SosRoute: typeof SosRoute
  SplashRoute: typeof SplashRoute
  StoriesRoute: typeof StoriesRoute
  StreakRoute: typeof StreakRoute
  VerifyRoute: typeof VerifyRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  AiBuilderResultRoute: typeof AiBuilderResultRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthTelegramRoute: typeof AuthTelegramRoute
  CommunitiesIdRoute: typeof CommunitiesIdRouteWithChildren
  CommunitiesNewRoute: typeof CommunitiesNewRoute
  MeetingsNewRoute: typeof MeetingsNewRoute
  UUserIdRoute: typeof UUserIdRoute
  AiBuilderIndexRoute: typeof AiBuilderIndexRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  MeetingsIndexRoute: typeof MeetingsIndexRoute
  MeetingsMeetingIdChatRoute: typeof MeetingsMeetingIdChatRoute
  MeetingsMeetingIdIndexRoute: typeof MeetingsMeetingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posters': {
      id: '/posters'
      path: '/posters'
      fullPath: '/posters'
      preLoaderRoute: typeof PostersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perks': {
      id: '/perks'
      path: '/perks'
      fullPath: '/perks'
      preLoaderRoute: typeof PerksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory-map': {
      id: '/memory-map'
      path: '/memory-map'
      fullPath: '/memory-map'
      preLoaderRoute: typeof MemoryMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways': {
      id: '/giveaways'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof GiveawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evening': {
      id: '/evening'
      path: '/evening'
      fullPath: '/evening'
      preLoaderRoute: typeof EveningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating': {
      id: '/dating'
      path: '/dating'
      fullPath: '/dating'
      preLoaderRoute: typeof DatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after-dark': {
      id: '/after-dark'
      path: '/after-dark'
      fullPath: '/after-dark'
      preLoaderRoute: typeof AfterDarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/': {
      id: '/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof MeetingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder/': {
      id: '/ai-builder/'
      path: '/ai-builder'
      fullPath: '/ai-builder/'
      preLoaderRoute: typeof AiBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof RoutesRoute
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/gallery': {
      id: '/profile/gallery'
      path: '/gallery'
      fullPath: '/profile/gallery'
      preLoaderRoute: typeof ProfileGalleryRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/meetings/new': {
      id: '/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof MeetingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating/filter': {
      id: '/dating/filter'
      path: '/filter'
      fullPath: '/dating/filter'
      preLoaderRoute: typeof DatingFilterRouteImport
      parentRoute: typeof DatingRoute
    }
    '/communities/new': {
      id: '/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof CommunitiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id': {
      id: '/communities/$id'
      path: '/communities/$id'
      fullPath: '/communities/$id'
      preLoaderRoute: typeof CommunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/telegram': {
      id: '/auth/telegram'
      path: '/auth/telegram'
      fullPath: '/auth/telegram'
      preLoaderRoute: typeof AuthTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/auth/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-builder/result': {
      id: '/ai-builder/result'
      path: '/ai-builder/result'
      fullPath: '/ai-builder/result'
      preLoaderRoute: typeof AiBuilderResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId/': {
      id: '/meetings/$meetingId/'
      path: '/meetings/$meetingId'
      fullPath: '/meetings/$meetingId/'
      preLoaderRoute: typeof MeetingsMeetingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/$meetingId/chat': {
      id: '/meetings/$meetingId/chat'
      path: '/meetings/$meetingId/chat'
      fullPath: '/meetings/$meetingId/chat'
      preLoaderRoute: typeof MeetingsMeetingIdChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$id/chat': {
      id: '/communities/$id/chat'
      path: '/chat'
      fullPath: '/communities/$id/chat'
      preLoaderRoute: typeof CommunitiesIdChatRouteImport
      parentRoute: typeof CommunitiesIdRoute
    }
  }
}

interface DatingRouteChildren {
  DatingFilterRoute: typeof DatingFilterRoute
}

const DatingRouteChildren: DatingRouteChildren = {
  DatingFilterRoute: DatingFilterRoute,
}

const DatingRouteWithChildren =
  DatingRoute._addFileChildren(DatingRouteChildren)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileGalleryRoute: typeof ProfileGalleryRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileGalleryRoute: ProfileGalleryRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RoutesRouteChildren {
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
}

const RoutesRouteChildren: RoutesRouteChildren = {
  RoutesRouteIdRoute: RoutesRouteIdRoute,
}

const RoutesRouteWithChildren =
  RoutesRoute._addFileChildren(RoutesRouteChildren)

interface CommunitiesIdRouteChildren {
  CommunitiesIdChatRoute: typeof CommunitiesIdChatRoute
}

const CommunitiesIdRouteChildren: CommunitiesIdRouteChildren = {
  CommunitiesIdChatRoute: CommunitiesIdChatRoute,
}

const CommunitiesIdRouteWithChildren = CommunitiesIdRoute._addFileChildren(
  CommunitiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfterDarkRoute: AfterDarkRoute,
  ChatsRoute: ChatsRoute,
  CityRoute: CityRoute,
  DatingRoute: DatingRouteWithChildren,
  EveningRoute: EveningRoute,
  GiveawaysRoute: GiveawaysRoute,
  HostRoute: HostRoute,
  MapRoute: MapRoute,
  MatchRoute: MatchRoute,
  MemoryMapRoute: MemoryMapRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  PerksRoute: PerksRoute,
  PostersRoute: PostersRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReportRoute: ReportRoute,
  RoutesRoute: RoutesRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  SosRoute: SosRoute,
  SplashRoute: SplashRoute,
  StoriesRoute: StoriesRoute,
  StreakRoute: StreakRoute,
  VerifyRoute: VerifyRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  AiBuilderResultRoute: AiBuilderResultRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthTelegramRoute: AuthTelegramRoute,
  CommunitiesIdRoute: CommunitiesIdRouteWithChildren,
  CommunitiesNewRoute: CommunitiesNewRoute,
  MeetingsNewRoute: MeetingsNewRoute,
  UUserIdRoute: UUserIdRoute,
  AiBuilderIndexRoute: AiBuilderIndexRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  MeetingsIndexRoute: MeetingsIndexRoute,
  MeetingsMeetingIdChatRoute: MeetingsMeetingIdChatRoute,
  MeetingsMeetingIdIndexRoute: MeetingsMeetingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
